var time;var editor=typeof editor!='undefined'?true:false;IS_TOUCH_DEVICE='ontouchstart'in window||navigator.msMaxTouchPoints;$(window).load(function(){if(!editor){}});function saveHtml(unsafe){return unsafe.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
$(document).ready(function(){if(!editor){$.ajax({url:'/actions/recordVisit',type:'PUT',data:JSON.stringify({referer:publicReferer,pageName:publicPageName})});if($('#made-with-simpsite').length>0){$(window).bind('load',function(){positionFooter();setTimeout(function(){positionFooter();},2000);});}
var footerTimeout;$(window).scroll(function(){clearTimeout(footerTimeout);footerTimeout=setTimeout(function(){positionFooter();},1000);}).resize(positionFooter);}
$(window).resize(function(){clearTimeout($.data(this,'resizeTimer'));$.data(this,'resizeTimer',setTimeout(function(){createMenuMore();hoverMenu();},1000));});$('.mobile-menu > ul li').each(function(){if($(this).find('.submenuNext').length>0){$(this).find('a').first().append('<span class="next"><span>&raquo;</span></span>');$(this).find('a .next').on('click',function(){if($(this).parent().parent().find('> .submenuNext').is(':visible')){$(this).parent().parent().find('> .submenuNext').slideUp(150);$(this).find('span').removeAttr('style');}else{$(this).parent().parent().find('> .submenuNext').slideDown();$(this).find('span').css('transform','rotate(90deg)').css('padding-left','3px');}
return false;});}});$('body').on('click','.mobile-menu .menu_button',function(){if($('.mobile-menu > ul').is(':visible')){$('.mobile-menu > ul').slideUp(150);$('.mobile-menu .menu_button').find('span').removeAttr('style');$('.mobile-menu > ul').find('.submenuNext').hide();$('.mobile-menu > ul').find('.next span').removeAttr('style');}else{$('.mobile-menu > ul').slideDown();$('.mobile-menu .menu_button').find('span:nth-child(2)').css('background-color','transparent');$('.mobile-menu .menu_button').find('span:nth-child(1)').css('transform','rotate(45deg)').css('margin','13px 0 6px -2px').css('width','27px').css('opacity','0.9');$('.mobile-menu .menu_button').find('span:nth-child(3)').css('transform','rotate(-45deg)').css('margin','-16px 0 6px -2px').css('width','27px').css('opacity','0.9');}});$('[data-uid="usersiteContent"] .element_reaction input[type="submit"]').on('click',function(){var submitButton=$(this);buttonStartLoading(submitButton);var elm=$(this).parents('.element_reaction');var name=elm.find('[name="name"]');var message=elm.find('[name="message"]');var reaction_id=$(this).attr('data-reaction-id');var errorMessage=$(this).attr('data-error');if(name.val()==''||message.val()==''){alert(languageStrings.reaction_error);buttonStopLoading(submitButton);return false;}
var data={reaction_id:reaction_id,name:name.val(),message:message.val()};$.ajax({url:'/actions/submitReaction',type:'POST',data:JSON.stringify(data),success:function(){elm.find('.inner').prepend('<div class="element_reaction_post"><div class="post"><div class="name-time"><span class="name"><strong>'+saveHtml(name.val())+'</strong></span> - <span class="time">'+languageStrings.reaction_now+'</span></div><div class="message">'+saveHtml(message.val()).replace(/\r\n|\r|\n/g,"<br />")+'</div></div></div>');name.val('');message.val('');buttonStopLoading(submitButton);elm.find('.no_messages').hide();$('html, body').animate({scrollTop:$(elm).find('.element_reaction_post').first().offset().top-10},1000);},error:function(response){if(response.status==400){buttonStopLoading(submitButton);alert(languageStrings.reaction_blocked);}
console.log(response);}});return false;});$('[data-uid="usersiteContent"] .element_form input[type="submit"]').on('click',function(){var submitButton=$(this);buttonStartLoading(submitButton);var elm=$(this).parents('.element_form');var form_id=$(this).attr('data-form-id');var sendData=[];var atLeastOneEmptyError=false;var emailError=false;$(elm).find('.input:not(.submit)').each(function(){var empty=false;var question=$(this).prev().find('label').clone().children().remove().end().text();if($(this).attr('data-type')=='text'||$(this).attr('data-type')=='email_address'){var answer=$(this).find('input').val();if($(this).find('input').val()==''&&$(this).attr('data-required')=='yes'){empty=true;}}else if($(this).attr('data-type')=='textarea'){var answer=$(this).find('textarea').val();if($(this).find('textarea').val()==''&&$(this).attr('data-required')=='yes'){empty=true;}}else if($(this).attr('data-type')=='radio'){var answer=$(this).find('[type="radio"]:checked').val();if($(this).find('input[type="radio"]:checked').length<1&&$(this).attr('data-required')=='yes'){empty=true;}}else if($(this).attr('data-type')=='checkbox'){var answer='';$(this).find('input[type="checkbox"]:checked').each(function(){answer+=' - '+$(this).val();});if($(this).find('input[type="checkbox"]:checked').length<1&&$(this).attr('data-required')=='yes'){empty=true;}}else if($(this).attr('data-type')=='select'){var answer=$(this).find('select option:selected').val();}
sendData.push({question:question,answer:answer});if(empty){atLeastOneEmptyError=true;$(this).prev().addClass('error_text');}else{$(this).prev().removeClass('error_text');if($(this).attr('data-type')=='email_address'&&$(this).find('input').val()!=''&&!/(.+)@(.+){2,}\.(.+){2,}/.test($(this).find('input').val())){emailError=true;$(this).prev().addClass('error_text');}}});if(atLeastOneEmptyError){formError(elm,languageStrings.form_required);buttonStopLoading(submitButton);return false;}else if(emailError){formError(elm,languageStrings.form_invalid_email);buttonStopLoading(submitButton);return false;}
var data={form_id:form_id,items:sendData};$.ajax({url:'/actions/submitForm',type:'POST',data:JSON.stringify(data),success:function(response){buttonStopLoading(submitButton);elm.find('form').hide();if(elm.find('.confirmation_text').text()==''){elm.find('.confirmation_text').text(languageStrings.form_default_confirm);}
elm.find('.confirmation_text').show();$('html, body').animate({scrollTop:$(elm).offset().top-10},1000);},error:function(response){if(response.status==400){buttonStopLoading(submitButton);formError(elm,languageStrings.form_blocked);}
console.log(response);}});return false;});$('[data-uid="usersiteContent"] .element_poll input[type="button"]').on('click',function(){var submitButton=$(this);buttonStartLoading(submitButton);var elm=$(this).parents('.element_poll');var poll_id=$(this).attr('data-poll-id');var answer_id=elm.find('.vote input[type="radio"]:checked').attr('data-answer-id');if(typeof answer_id=='undefined'){alert(languageStrings.poll_error);buttonStopLoading(submitButton);return;}
var data={poll_id:poll_id,answer_id:answer_id};$.ajax({url:'/actions/pollVote',type:'POST',data:JSON.stringify(data),success:function(response){buttonStopLoading(submitButton);elm.find('input').hide();if(typeof response=='undefined'||response.length<1){elm.find('.inner').hide();elm.append('<div>Bedankt voor het stemmen</div>');return;}
elm.find('.result').show();var number=elm.find('.vote input[type="radio"]:checked').parents('.vote').find('.percentage div');number.text(parseInt(number.text())+1);var totalVotes=0;elm.find('.percentage div').each(function(){totalVotes+=parseInt($(this).text())});elm.find('.percentage').each(function(){var widthPercentage=(parseInt($(this).find('div').text())/totalVotes)*100;$(this).css('width',widthPercentage+'%');});},error:function(response){console.log(response);alert('Error');}});});$('[data-uid="usersiteContent"], #site_window').on('click','.element_gallery .thumbs  div',function(e){var elm=this;var parent=$(this).parents('.element_gallery');changeGalleryImage(parent,elm);});$('[data-uid="usersiteContent"], #site_window').on('click','.element_gallery .next, .element_gallery .back',function(e){var parent=$(this).parents('.element_gallery');var currentId=parent.find('.large img').attr('data-id');parent.find('.next, .back').show();if($(this).hasClass('next')){var img=parent.find('.thumbs [data-id="'+currentId+'"]').parent().next();if(img.is(':last-child')){parent.find('.next').hide();}}else{var img=parent.find('.thumbs [data-id="'+currentId+'"]').parent().prev();if(img.is(':first-child')){parent.find('.back').hide();}}
parent.find('.large img').attr('data-id',img.find('[data-id]').attr('data-id'));changeGalleryImage(parent,img);});$('[data-uid="usersiteContent"], #site_window').on('click','.element_reaction .more input[type="button"]',function(e){var elm=$(this).parents('.element_reaction');var submitButton=$(this);buttonStartLoading(submitButton);if(elm.find('.messages .inner > div').length>0){limit=5;}else{limit=editor?elm.attr('data-limit'):elm.find('input[type="submit"]').attr('data-limit');}
var data={reaction_id:editor?elm.attr('data-reaction-id'):elm.find('input[type="submit"]').attr('data-reaction-id'),offset:editor?elm.attr('data-offset'):elm.find('input[type="submit"]').attr('data-offset'),limit:limit}
var url=editor?'/editor/'+site_id+'/reactions/loadMessages':'/actions/loadReactions';$.ajax({url:url,type:'PUT',data:JSON.stringify(data),success:function(response){buttonStopLoading(submitButton);if(elm.find('.messages .inner > div').length>0){if(editor){elm.attr('data-offset',parseInt(elm.attr('data-offset'))+5);}else{elm.find('input[type="submit"]').attr('data-offset',parseInt(elm.find('input[type="submit"]').attr('data-offset'))+5);}}else{if(editor){elm.attr('data-offset',parseInt(elm.attr('data-limit')));}else{elm.find('input[type="submit"]').attr('data-offset',parseInt(elm.find('input[type="submit"]').attr('data-limit')));}}
placeReactionMessages(elm,response);},error:function(response){console.log(response);alert(response.responseJSON.error);}});});});function createMenuMore(){var THRESHOLD_TOP=5;$menu=$('[data-uid="usersiteMenu"]'),$menuItems=$menu.children('li');if($menuItems.length==0||$menuItems.eq(0).length==0||$menuItems.eq(1).length==0){return;}
var topFirstItem=$menu.children('li').first().position().top+THRESHOLD_TOP,addMoreButton=function(){moreButton="<li class='more-li'><a href='#' class='more-menu'>Meer...</a><ul class='submenuNext'></ul></li>";if($menu.find('.language_selector').length>0){$(moreButton).insertBefore($menu.find('.language_selector').first());}else{$menu.append(moreButton);}},addMoreItem=function($li){var liAttrId=$li.attr('data-id'),pageId=typeof liAttrId!='undefined'&&liAttrId!=false?'data-id="'+liAttrId+'"':'';element='<li '+pageId+'>'+$li.html()+'</li>';$menu.find('> .more-li > .submenuNext').prepend(element);$li.hide();},wrongPosition=function(){if(typeof $menu.children('li:visible:last-child').position()=='undefined'){return false;}
return $menu.children('li:visible:last-child').position().top>topFirstItem;};if(topFirstItem!=$menuItems.eq(1).position().top+THRESHOLD_TOP){return;}
$menu.find('.more-li').remove();$menuItems.css('display','');if(wrongPosition()){addMoreButton();var checkMenuItems=$($menuItems).slice(1).not('.more-li').not('.language_selector');$(checkMenuItems.get().reverse()).each(function(){if(!wrongPosition()){return false;}
addMoreItem($(this));});}}
function checkMenuMore(count){count=typeof count!='undefined'?count:0;if(count>5){return;}
setTimeout(function(){console.log('checking...');if($('[data-uid="usersiteMenu"] li').length>0&&typeof $('[data-uid="usersiteMenu"]').children('li:visible:last-child').position()!='undefined'&&$('[data-uid="usersiteMenu"]').children('li:visible:last-child').position().top>$menu.children('li:first-child').position().top+5){createMenuMore();count++;console.log('redo menu'+count);checkMenuMore(count);}else{console.log('ok');}},500);}
function hoverMenu(){$('[data-uid="usersiteMenu"] ul').find('.moreUlSign').remove();$('[data-uid="usersiteMenu"] ul li:has(ul) > a').append('<span class="moreUlSign">&raquo;</span>');$('[data-uid="usersiteMenu"] li').unbind('mouseenter mouseleave');if(IS_TOUCH_DEVICE){$('[data-uid="usersiteMenu"] li').unbind('touchstart');$('[data-uid="usersiteMenu"] li').on('touchstart',function(e){$li=$(this);if($li.find('> ul.submenuNext:hidden').length>0){e.preventDefault();$li.trigger('mouseenter');$('body').unbind('click.touchMenu');$('body').one('click.touchMenu',function(){$li.trigger('mouseout');});return false;}});}
$('[data-uid="usersiteMenu"] li').hover(function()
{var elm=$(this);var toOpen=$(this).find('ul').first();var hoverLi=toOpen.parent().parent();if(toOpen.is(':hidden'))
{$(this).parent().find('ul').not(toOpen).hide();}
clearTimeout($(this).data('timeInOut'));if(toOpen.hasClass('submenuNext')&&hoverLi.hasClass('submenuNext'))
{var width=hoverLi.outerWidth();var offset=hoverLi.offset();var hoverOffset=toOpen.parent().offset();if(($(window).width()-(offset.left+width))>222){var left=220;}
else
{var left=-220;}
toOpen.css({top:3,marginLeft:left+"px"});}
else
{var width=elm.outerWidth();var offset=elm.offset();var hoverOffset=toOpen.parent().offset();if(($(window).width()-(offset.left+width))>222){var left=parseInt(elm.css('margin-left'));if(elm.parents('[data-id="custom_layout_sidebar"]:not(.top)').length>0){var menuWidth=elm.parents('[data-uid="usersiteMenu"]').outerWidth();left=left+menuWidth;}}
else
{var left=-220+elm.width();if(elm.parents('[data-id="custom_layout_sidebar"]:not(.top)').length>0){var menuWidth=elm.parents('[data-uid="usersiteMenu"]').outerWidth();left=left-menuWidth;}}
toOpen.css({marginLeft:left+"px"});}
toOpen.fadeIn(200);},function()
{var $elm=$(this);$(this).data('timeInOut',setTimeout(function()
{$elm.find('ul').first().hide();},450))});}
function placeReactionMessages(elm,data){if(data.messages.length>0){$.each(data.messages,function(index,post){var postElm=editor?$('<div class="element_reaction_post"><div class="post"><div class="name-time"><span class="name"><strong></strong></span> - <span class="time"></span><div class="actions"><span data-action="delete_message">Verwijder</span><span data-action="block_message">Blokkeer</span></div></div><div class="message"></div></div></div>'):$('<div class="element_reaction_post"><div class="post"><div class="name-time"><span class="name"><strong></strong></span> - <span class="time"></span></div><div class="message"></div></div></div>');postElm.attr('data-message-id',post.id);postElm.find('.name strong').html(post.name);postElm.find('.time').html(post.time);postElm.find('.message').html(nl2br(post.message));elm.find('.messages .inner').append(postElm);});if(data.show_more==true){elm.find('.more').show();}else{elm.find('.more').hide();}}else{elm.find('.no_messages').show();elm.find('.more').hide();}}
function nl2br(str,is_xhtml){var breakTag=(is_xhtml||typeof is_xhtml==='undefined')?'<br />':'<br>';return(str+'').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,'$1'+breakTag+'$2');}
function changeGalleryImage(gallery,image){gallery.find('.large img').fadeOut(150,function(){gallery.find('.large img').attr('src','');gallery.find('.large img').attr('src',$(image).find('img').attr('data-original'));gallery.find('.large img').fadeIn(150);});gallery.find('.title').fadeOut(150,function(){if($(image).find('img').attr('data-title')==''){gallery.find('.title').hide();}else{gallery.find('.title').html($(image).find('img').attr('data-title')).fadeIn(150);}});}
function formError(elm,message){elm.find('.error').html(message);if(elm.find('.error').is(':visible')){elm.find('.error').fadeOut(90,function(){$(this).fadeIn(90);});}else{elm.find('.error').slideDown(100);}}
function buttonStartLoading(button){button.attr('data-original',button.val()).attr('disabled','disabled').val(languageStrings.loading);}
function buttonStopLoading(button){button.removeAttr('disabled').val(button.attr('data-original'));}
function positionFooter(){console.log('stick it');var $adBar=$('#made-with-simpsite');$adBar.css('top','0px');if($adBar.length>0&&($adBar.offset().top+$adBar.outerHeight())<$(window).height()){var top=$(document).height()-$adBar.offset().top-$adBar.outerHeight();$adBar.css('top',top+'px');}}